cabal-version:      3.0
name:               trails
version:            0.1.0.0
license:            BSD-3-Clause
license-file:       LICENSE
author:             Claire Barnes
maintainer:         claire@claire-barnes.com
build-type:         Simple

common warnings
    ghc-options: -Wall

executable trails
    import:           warnings
    main-is:          Trails.hs
    build-depends:
      base ^>=4.22.0.0,
      ghc-experimental ^>=9.1401.0
    hs-source-dirs:   app
    default-language: Haskell2010
    ghc-options:
      -no-hs-main
      -optl-mexec-model=reactor
      "-optl-Wl,--export=hs_init,--export=hs_init,--export=draw"

